version: "3.9"

services:
  server-staging:
    build: 
      context: ./server
      target: prod
    container_name: node-server-staging
    env_file: 
      - ./server/.env.staging
    networks:
      - app-network

  admin-staging:
    build: 
      context: ./admin-panel
      target: prod
    container_name: admin-staging
    env_file:
      - ./admin-panel/.env.staging
    networks:
      - app-network

  frontend-staging:
    build: 
      context: ./client
      target: prod
      args:
        NEXT_PUBLIC_API_URL: https://stagingapi.pickmymaid.com/
        NEXT_PUBLIC_DISABLE_API_DURING_BUILD: true
    container_name: frontend-staging
    env_file:
      - ./client/.env.staging
    depends_on:
      - server-staging
    networks:
      - app-network

  haproxy-staging:
    image: haproxy:2.8-alpine
    container_name: haproxy-staging
    ports:
      - "8443:443"   # staging mapped to 8443 on host
    volumes:
      - ./haproxy/haproxy.cfg.staging:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - frontend-staging
      - admin-staging
      - server-staging
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
