name: Deploy to Digital Ocean

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Create known_hosts file and add Digital Ocean host key
        run: |
          mkdir -p ~/.ssh && \
          touch ~/.ssh/known_hosts && \
          ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
            
      - name: Add GitHub Host Key to Known Hosts
        run: ssh-keyscan github.com >> ~/.ssh/known_hosts    

      - name: Install dependencies
        run: npm install

      - name: Build and Deploy
        run: |
          npm run build  # If you have a build step
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "cd pickmymaid-backend/ && git pull origin master && npm install && pm2 restart src/server.ts && sudo service nginx restart"

        env:
          DO_ACCESS_TOKEN: ${{ secrets.DO_SECRET }}
